source 'https://rubygems.org'

gem 'chef-lxc'
gem 'irbtools'
gem 'pry'
gem 'rspec'
gem 'librarian-chef'
gem 'rake'
gem 'pd-blender', github: 'PagerDuty/blender'
gem 'blender-chef', github: 'PagerDuty/blender-chef'
gem 'blender-serf', github: 'PagerDuty/blender-serf'
